In [14]:
import os
import sys
sys.path.append('%s/../' % os.getcwd())

import pandas as pd
import numpy as np
import datetime

from helper import feriados
from db import conexao
c = conexao.Conexao()
connection = c.con

import formulas_tb as tb
from formulas_aux import dict_meses

Você está conectando em outro computador
Conexao <Engine(mysql+mysqldb://guilherme:***@datascience2:3306/breakdown-fundos?charset=utf8)>

In [15]:
df_table = c.query('select * from map_rf_cmarkets')

select * from map_rf_cmarkets

# Primeira Parte: Duration dos títulos abertos - anbima

http://www.anbima.com.br/vna/

In [16]:
data=pd.to_datetime(datetime.date.today())
dict_tp={
    'LFT':0.0,
    'LTN':0.0,
    'NTN-B':0.06,
    'NTN-C':0.06,
    'NTN-F':0.06
}
dict_vna={
    'NTN-B':3000.006193,
    'NTN-C':3505.867748,
    'LFT':9026.492562,
    'LTN':1.0,
    'NTN-F':1.0
}

In [17]:
df=df_table[df_table['periodo']=='anbima'].copy()
df=df[df['data']==df['data'].max()]
df=df[['titulo','vencimento','compra','venda','tx_indicativa']].reset_index(drop=True)

df['cupom']=[dict_tp[df['titulo'][i]] for i in range(0,len(df))]
df['vna']=[dict_vna[df['titulo'][i]] for i in range(0,len(df))]

feriados = list(feriados.lista())
df['data_atual']=data

df['pu']=[tb.titulos(data,df['vencimento'][i],df['tx_indicativa'][i]/100,'pu',df['cupom'][i],
                  vna=df['vna'][i]) for i in range(0,len(df))]

df['mod']=[tb.titulos(data,df['vencimento'][i],df['tx_indicativa'][i]/100,'mod',
                   df['cupom'][i],vna=df['vna'][i]) for i in range(0,len(df))]


df

,titulo,vencimento,compra,venda,tx_indicativa,cupom,vna,data_atual,pu,mod
0,LFT,2017-09-07,0.0000,0.0000,0.0000,0.00,9026.492562,2017-08-15,1.000000e+03,0.067460
1,LFT,2018-03-01,0.0000,0.0000,0.0022,0.00,9026.492562,2017-08-15,9.999883e+02,0.531746
2,LFT,2018-09-01,0.0000,0.0000,0.0017,0.00,9026.492562,2017-08-15,9.999823e+02,1.043651
3,LFT,2019-03-01,0.0000,0.0000,0.0039,0.00,9026.492562,2017-08-15,9.999403e+02,1.531746
4,LFT,2020-03-01,0.0000,0.0000,0.0095,0.00,9026.492562,2017-08-15,9.997599e+02,2.527778
5,LFT,2020-09-01,0.0000,0.0000,0.0103,0.00,9026.492562,2017-08-15,9.996878e+02,3.031746
6,LFT,2021-03-01,0.0000,0.0000,0.0118,0.00,9026.492562,2017-08-15,9.995852e+02,3.515873
7,LFT,2021-09-01,0.0000,0.0000,0.0119,0.00,9026.492562,2017-08-15,9.995208e+02,4.027778
8,LFT,2022-03-01,0.0000,0.0000,0.0120,0.00,9026.492562,2017-08-15,9.994578e+02,4.519841
9,LFT,2022-09-01,0.0000,0.0000,0.0120,0.00,9026.492562,2017-08-15,9.993969e+02,5.027778
10,LFT,2023-03-01,0.0000,0.0000,0.0119,0.00,9026.492562,2017-08-15,9.993439e+02,5.515873
11,LFT,2023-09-01,0.0000,0.0000,0.0119,0.00,9026.492562,2017-08-15,9.992835e+02,6.023810
12,LTN,2017-10-01,8.7531,8.7460,8.7504,0.00,1.000000,2017-08-15,9.890752e+02,0.130952
13,LTN,2018-01-01,8.1174,8.0950,8.1051,0.00,1.000000,2017-08-15,9.713480e+02,0.373016
14,LTN,2018-04-01,7.9350,7.9250,7.9300,0.00,1.000000,2017-08-15,9.541462e+02,0.615079
15,LTN,2018-07-01,7.8800,7.8700,7.8750,0.00,1.000000,2017-08-15,9.365283e+02,0.865079
16,LTN,2018-10-01,7.9480,7.9400,7.9449,0.00,1.000000,2017-08-15,9.180054e+02,1.119048
17,LTN,2019-01-01,8.0640,8.0550,8.0600,0.00,1.000000,2017-08-15,8.995901e+02,1.365079
18,LTN,2019-04-01,8.2586,8.2500,8.2549,0.00,1.000000,2017-08-15,8.803145e+02,1.607143
19,LTN,2019-07-01,8.4486,8.4398,8.4436,0.00,1.000000,2017-08-15,8.605200e+02,1.853175
20,LTN,2019-10-01,8.6736,8.6661,8.6700,0.00,1.000000,2017-08-15,8.387358e+02,2.115079
21,LTN,2020-01-01,8.8129,8.8050,8.8100,0.00,1.000000,2017-08-15,8.187095e+02,2.369048
22,LTN,2020-07-01,9.1425,9.1350,9.1391,0.00,1.000000,2017-08-15,7.789053e+02,2.857143
23,LTN,2021-07-01,9.6100,9.6032,9.6069,0.00,1.000000,2017-08-15,7.022595e+02,3.853175
24,NTN-B,2018-08-15,3.3531,3.3305,3.3500,0.06,3000.006193,2017-08-15,3.076623e+06,0.041949
25,NTN-B,2019-05-15,3.5213,3.5035,3.5123,0.06,3000.006193,2017-08-15,3.169385e+06,0.106070
26,NTN-B,2020-08-15,4.2600,4.2362,4.2500,0.06,3000.006193,2017-08-15,3.144422e+06,0.269683
27,NTN-B,2021-05-15,4.5434,4.5273,4.5346,0.06,3000.006193,2017-08-15,3.193578e+06,0.393084
28,NTN-B,2022-08-15,4.8085,4.7888,4.7976,0.06,3000.006193,2017-08-15,3.157914e+06,0.654147
29,NTN-B,2023-03-15,0.0000,0.0000,4.9047,0.06,3000.006193,2017-08-15,3.232433e+06,0.772636
30,NTN-B,2023-05-15,4.9105,4.8934,4.9045,0.06,3000.006193,2017-08-15,3.207724e+06,0.820016
31,NTN-B,2024-08-15,4.9300,4.9080,4.9212,0.06,3000.006193,2017-08-15,3.189208e+06,1.157381
32,NTN-B,2026-08-15,5.0967,5.0811,5.0900,0.06,3000.006193,2017-08-15,3.194281e+06,1.753208
33,NTN-B,2030-08-15,5.1902,5.1371,5.1727,0.06,3000.006193,2017-08-15,3.233814e+06,3.115073
34,NTN-B,2035-05-15,5.2194,5.1863,5.2066,0.06,3000.006193,2017-08-15,3.319502e+06,4.813276
35,NTN-B,2040-08-15,5.2240,5.1870,5.2133,0.06,3000.006193,2017-08-15,3.315340e+06,6.841716
36,NTN-B,2045-05-15,5.3068,5.2600,5.2900,0.06,3000.006193,2017-08-15,3.355394e+06,8.409394
37,NTN-B,2050-08-15,5.2700,5.2500,5.2600,0.06,3000.006193,2017-08-15,3.348820e+06,10.238410
38,NTN-B,2055-05-15,5.2392,5.1967,5.2200,0.06,3000.006193,2017-08-15,3.431761e+06,11.493718
39,NTN-C,2021-04-01,0.0000,0.0000,4.4466,0.06,3505.867748,2017-08-15,3.762141e+06,0.368286
40,NTN-C,2031-01-01,0.0000,0.0000,5.0900,0.06,3505.867748,2017-08-15,3.837884e+06,3.227927
41,NTN-F,2018-01-01,8.1313,8.1197,8.1259,0.06,1.000000,2017-08-15,9.999922e+02,0.981997
42,NTN-F,2019-01-01,8.0191,7.9923,8.0060,0.06,1.000000,2017-08-15,9.832002e+02,0.987768
43,NTN-F,2021-01-01,9.2536,9.2441,9.2485,0.06,1.000000,2017-08-15,9.187250e+02,1.148823
44,NTN-F,2023-01-01,9.7692,9.7600,9.7650,0.06,1.000000,2017-08-15,8.588517e+02,1.478005
45,NTN-F,2025-01-01,9.9719,9.9584,9.9649,0.06,1.000000,2017-08-15,8.112166e+02,1.936539
46,NTN-F,2027-01-01,10.0439,10.0329,10.0375,0.06,1.000000,2017-08-15,7.741213e+02,2.486631

# Segunda Parte - Carteira fundos Rio Bravo

In [11]:
fundos = tb.DurationFundos(data,dict_tp,dict_vna).duration_carteiras(data,dict_tp,dict_vna)

TypeError: __init__() takes exactly 4 arguments (1 given)

In [ ]:
fundos['cupom']=[dict_tp[fundos['classe_ativo'][i]] for i in range(0,len(fundos))]
fundos['vna']=[dict_vna[fundos['classe_ativo'][i]] for i in range(0,len(fundos))]
fundos['mod']=[titulos(fundos['date'][i],fundos['vencimento'][i],fundos['pu'][i],'mod',fundos['cupom'][i],vna=fundos['vna'][i]) 
                 for i in range(0,len(fundos))]


dict_pl={
    "RIO BRAVO APOLLO FIM":48049518.00,
    "RIO BRAVO JUROS MASTER FI RF":24774574.00,
    "RIO BRAVO PREVIDENCIA FIM":17845756.00
}
fundos['pct_mod']=[fundos['posicao_atual'][i]/dict_pl[fundos['fundo'][i]]*fundos['mod'][i] for i in range(0,len(fundos))]

In [ ]:
fundos[['fundo','mod','pct_mod']].groupby(by='fundo').sum()