In [1]:
%%time

%load_ext autoreload
%autoreload 2

import os
import sys
sys.path.append('%s/../' % os.getcwd())

import datetime
import pandas as pd
import numpy as np

from db import conexao
c = conexao.Conexao()
connection = c.con

%matplotlib inline


# query da tabela de SCS
tb_scs = c.query('select * from assets_precofuturo where codigo="SCS" or codigo="SCC" '\
                 'and tipo_serie="*" '\
                 'and date>="2004-01-01"')

Você está conectando em outro computador
Conexao <Engine(mysql+mysqldb://guilherme:***@datascience2:3306/breakdown-fundos?charset=utf8)>
select * from assets_precofuturo where codigo="SCS" or codigo="SCC" and tipo_serie="*" and date>="2004-01-01"
Wall time: 44.2 s

In [2]:
estoque_aberto=tb_scs[['date','data_liquidacao_financeira','codigo','volume_uss','qtd_contratos_aberto',
       'qtd_contratos_negociados_dia']].sort_values(by='date').copy()
estoque_aberto['qtd_contratos_aberto']=np.where(estoque_aberto['codigo']=='SCC',
                                         estoque_aberto['qtd_contratos_aberto']*-1.0,estoque_aberto['qtd_contratos_aberto'])
estoque_aberto['qtd_contratos_aberto']=estoque_aberto['qtd_contratos_aberto']/20.0




pvt_hist = pd.pivot_table(estoque_aberto, values=['qtd_contratos_aberto'],
                     index='date', columns='data_liquidacao_financeira')
pvt_hist=pvt_hist.fillna(0)

In [6]:
estoque_aberto[estoque_aberto['date']==estoque_aberto['date'].max()].sort_values('data_liquidacao_financeira').drop_duplicates()

,date,data_liquidacao_financeira,codigo,volume_uss,qtd_contratos_aberto,qtd_contratos_negociados_dia
46258,2017-07-12,2017-08-01,SCS,0.0,6181.00,0.0
46255,2017-07-12,2017-10-02,SCS,0.0,8204.75,0.0
46256,2017-07-12,2018-01-02,SCS,0.0,8046.00,0.0
46257,2017-07-12,2018-04-02,SCS,0.0,5332.50,0.0

In [7]:
pvt_hist

                           qtd_contratos_aberto                        \
data_liquidacao_financeira           2004-01-05 2004-01-22 2004-02-03
date
2004-01-02                              -2758.5    -967.45   -2832.25
2004-01-05                                  0.0    -967.45   -2832.25
2004-01-06                                  0.0    -967.45   -2832.25
2004-01-07                                  0.0    -967.45   -2832.25
2004-01-08                                  0.0    -967.45   -2832.25
2004-01-09                                  0.0    -967.45   -2832.25
2004-01-12                                  0.0    -967.45   -2832.25
2004-01-13                                  0.0    -967.45   -2832.25
2004-01-14                                  0.0    -967.45   -2832.25
2004-01-15                                  0.0    -967.45   -2832.25
2004-01-16                                  0.0    -967.45   -2832.25
2004-01-19                                  0.0    -967.45   -2832.25
2004-01-20                                  0.0    -967.45   -2832.25
2004-01-21                                  0.0    -967.45   -2832.25
2004-01-22                                  0.0       0.00   -2832.25
2004-01-23                                  0.0       0.00   -2832.25
2004-01-26                                  0.0       0.00   -2832.25
2004-01-27                                  0.0       0.00   -2872.25
2004-01-28                                  0.0       0.00   -2922.25
2004-01-29                                  0.0       0.00   -2922.25
2004-01-30                                  0.0       0.00   -2922.25
2004-02-02                                  0.0       0.00   -2922.25
2004-02-03                                  0.0       0.00       0.00
2004-02-04                                  0.0       0.00       0.00
2004-02-05                                  0.0       0.00       0.00
2004-02-06                                  0.0       0.00       0.00
2004-02-09                                  0.0       0.00       0.00
2004-02-10                                  0.0       0.00       0.00
2004-02-11                                  0.0       0.00       0.00
2004-02-12                                  0.0       0.00       0.00
...                                         ...        ...        ...
2017-05-31                                  0.0       0.00       0.00
2017-06-01                                  0.0       0.00       0.00
2017-06-02                                  0.0       0.00       0.00
2017-06-05                                  0.0       0.00       0.00
2017-06-06                                  0.0       0.00       0.00
2017-06-07                                  0.0       0.00       0.00
2017-06-08                                  0.0       0.00       0.00
2017-06-09                                  0.0       0.00       0.00
2017-06-12                                  0.0       0.00       0.00
2017-06-13                                  0.0       0.00       0.00
2017-06-14                                  0.0       0.00       0.00
2017-06-16                                  0.0       0.00       0.00
2017-06-19                                  0.0       0.00       0.00
2017-06-20                                  0.0       0.00       0.00
2017-06-21                                  0.0       0.00       0.00
2017-06-22                                  0.0       0.00       0.00
2017-06-23                                  0.0       0.00       0.00
2017-06-26                                  0.0       0.00       0.00
2017-06-27                                  0.0       0.00       0.00
2017-06-28                                  0.0       0.00       0.00
2017-06-29                                  0.0       0.00       0.00
2017-06-30                                  0.0       0.00       0.00
2017-07-03                                  0.0       0.00       0.00
2017-07-04                                  0.0       0.00       0.00
2017-07-05                                  0.0       0.00       0.00
2017-07-06                                  0.0       0.00       0.00
2017-07-07                                  0.0       0.00       0.00
2017-07-10                                  0.0       0.00       0.00
2017-07-11                                  0.0       0.00       0.00
2017-07-12                                  0.0       0.00       0.00

                                                                        \
data_liquidacao_financeira 2004-03-02 2004-04-02 2004-05-20 2004-07-02
date
2004-01-02                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-05                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-06                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-07                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-08                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-09                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-12                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-13                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-14                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-15                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-16                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-19                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-20                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-21                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-22                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-23                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-26                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-27                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-28                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-29                     -261.0    -2632.0    -2012.2   -2906.25
2004-01-30                     -261.0    -2632.0    -2012.2   -2906.25
2004-02-02                     -261.0    -2632.0    -2012.2   -2906.25
2004-02-03                     -261.0    -2632.0    -2012.2   -2906.25
2004-02-04                     -361.0    -2632.0    -2012.2   -2906.25
2004-02-05                     -361.0    -2632.0    -2012.2   -2906.25
2004-02-06                     -361.0    -2632.0    -2012.2   -2906.25
2004-02-09                     -361.0    -2632.0    -2012.2   -2906.25
2004-02-10                     -361.0    -2632.0    -2012.2   -2906.25
2004-02-11                     -461.0    -2632.0    -2012.2   -2906.25
2004-02-12                     -461.0    -2632.0    -2012.2   -2906.25
...                               ...        ...        ...        ...
2017-05-31                        0.0        0.0        0.0       0.00
2017-06-01                        0.0        0.0        0.0       0.00
2017-06-02                        0.0        0.0        0.0       0.00
2017-06-05                        0.0        0.0        0.0       0.00
2017-06-06                        0.0        0.0        0.0       0.00
2017-06-07                        0.0        0.0        0.0       0.00
2017-06-08                        0.0        0.0        0.0       0.00
2017-06-09                        0.0        0.0        0.0       0.00
2017-06-12                        0.0        0.0        0.0       0.00
2017-06-13                        0.0        0.0        0.0       0.00
2017-06-14                        0.0        0.0        0.0       0.00
2017-06-16                        0.0        0.0        0.0       0.00
2017-06-19                        0.0        0.0        0.0       0.00
2017-06-20                        0.0        0.0        0.0       0.00
2017-06-21                        0.0        0.0        0.0       0.00
2017-06-22                        0.0        0.0        0.0       0.00
2017-06-23                        0.0        0.0        0.0       0.00
2017-06-26                        0.0        0.0        0.0       0.00
2017-06-27                        0.0        0.0        0.0       0.00
2017-06-28                        0.0        0.0        0.0       0.00
2017-06-29                        0.0        0.0        0.0       0.00
2017-06-30                        0.0        0.0        0.0       0.00
2017-07-03                        0.0        0.0        0.0       0.00
2017-07-04                        0.0        0.0        0.0       0.00
2017-07-05                        0.0        0.0        0.0       0.00
2017-07-06                        0.0        0.0        0.0       0.00
2017-07-07                        0.0        0.0        0.0       0.00
2017-07-10                        0.0        0.0        0.0       0.00
2017-07-11                        0.0        0.0        0.0       0.00
2017-07-12                        0.0        0.0        0.0       0.00

                                                               ...      \
data_liquidacao_financeira 2004-07-08 2004-10-04 2004-10-14    ...
date                                                           ...
2004-01-02                     -172.5     -541.2     -400.0    ...
2004-01-05                     -172.5     -541.2     -400.0    ...
2004-01-06                     -172.5     -541.2     -400.0    ...
2004-01-07                     -172.5     -541.2     -400.0    ...
2004-01-08                     -172.5     -541.2     -400.0    ...
2004-01-09                     -172.5     -541.2     -400.0    ...
2004-01-12                     -172.5     -541.2     -400.0    ...
2004-01-13                     -172.5     -541.2     -400.0    ...
2004-01-14                     -172.5     -541.2     -400.0    ...
2004-01-15                     -172.5     -541.2     -400.0    ...
2004-01-16                     -172.5     -541.2     -400.0    ...
2004-01-19                     -172.5     -541.2     -400.0    ...
2004-01-20                     -172.5     -541.2     -400.0    ...
2004-01-21                     -172.5     -541.2     -400.0    ...
2004-01-22                     -172.5     -541.2     -400.0    ...
2004-01-23                     -172.5     -541.2     -400.0    ...
2004-01-26                     -172.5     -541.2     -400.0    ...
2004-01-27                     -172.5     -541.2     -400.0    ...
2004-01-28                     -172.5     -541.2     -400.0    ...
2004-01-29                     -172.5     -541.2     -400.0    ...
2004-01-30                     -172.5     -541.2     -400.0    ...
2004-02-02                     -172.5     -541.2     -400.0    ...
2004-02-03                     -172.5     -541.2     -400.0    ...
2004-02-04                     -172.5     -541.2     -400.0    ...
2004-02-05                     -172.5     -541.2     -400.0    ...
2004-02-06                     -172.5     -541.2     -400.0    ...
2004-02-09                     -172.5     -541.2     -400.0    ...
2004-02-10                     -172.5     -541.2     -400.0    ...
2004-02-11                     -172.5     -541.2     -400.0    ...
2004-02-12                     -172.5     -541.2     -400.0    ...
...                               ...        ...        ...    ...
2017-05-31                        0.0        0.0        0.0    ...
2017-06-01                        0.0        0.0        0.0    ...
2017-06-02                        0.0        0.0        0.0    ...
2017-06-05                        0.0        0.0        0.0    ...
2017-06-06                        0.0        0.0        0.0    ...
2017-06-07                        0.0        0.0        0.0    ...
2017-06-08                        0.0        0.0        0.0    ...
2017-06-09                        0.0        0.0        0.0    ...
2017-06-12                        0.0        0.0        0.0    ...
2017-06-13                        0.0        0.0        0.0    ...
2017-06-14                        0.0        0.0        0.0    ...
2017-06-16                        0.0        0.0        0.0    ...
2017-06-19                        0.0        0.0        0.0    ...
2017-06-20                        0.0        0.0        0.0    ...
2017-06-21                        0.0        0.0        0.0    ...
2017-06-22                        0.0        0.0        0.0    ...
2017-06-23                        0.0        0.0        0.0    ...
2017-06-26                        0.0        0.0        0.0    ...
2017-06-27                        0.0        0.0        0.0    ...
2017-06-28                        0.0        0.0        0.0    ...
2017-06-29                        0.0        0.0        0.0    ...
2017-06-30                        0.0        0.0        0.0    ...
2017-07-03                        0.0        0.0        0.0    ...
2017-07-04                        0.0        0.0        0.0    ...
2017-07-05                        0.0        0.0        0.0    ...
2017-07-06                        0.0        0.0        0.0    ...
2017-07-07                        0.0        0.0        0.0    ...
2017-07-10                        0.0        0.0        0.0    ...
2017-07-11                        0.0        0.0        0.0    ...
2017-07-12                        0.0        0.0        0.0    ...

                                                                        \
data_liquidacao_financeira 2017-02-01 2017-03-01 2017-04-03 2017-05-02
date
2004-01-02                        0.0        0.0        0.0        0.0
2004-01-05                        0.0        0.0        0.0        0.0
2004-01-06                        0.0        0.0        0.0        0.0
2004-01-07                        0.0        0.0        0.0        0.0
2004-01-08                        0.0        0.0        0.0        0.0
2004-01-09                        0.0        0.0        0.0        0.0
2004-01-12                        0.0        0.0        0.0        0.0
2004-01-13                        0.0        0.0        0.0        0.0
2004-01-14                        0.0        0.0        0.0        0.0
2004-01-15                        0.0        0.0        0.0        0.0
2004-01-16                        0.0        0.0        0.0        0.0
2004-01-19                        0.0        0.0        0.0        0.0
2004-01-20                        0.0        0.0        0.0        0.0
2004-01-21                        0.0        0.0        0.0        0.0
2004-01-22                        0.0        0.0        0.0        0.0
2004-01-23                        0.0        0.0        0.0        0.0
2004-01-26                        0.0        0.0        0.0        0.0
2004-01-27                        0.0        0.0        0.0        0.0
2004-01-28                        0.0        0.0        0.0        0.0
2004-01-29                        0.0        0.0        0.0        0.0
2004-01-30                        0.0        0.0        0.0        0.0
2004-02-02                        0.0        0.0        0.0        0.0
2004-02-03                        0.0        0.0        0.0        0.0
2004-02-04                        0.0        0.0        0.0        0.0
2004-02-05                        0.0        0.0        0.0        0.0
2004-02-06                        0.0        0.0        0.0        0.0
2004-02-09                        0.0        0.0        0.0        0.0
2004-02-10                        0.0        0.0        0.0        0.0
2004-02-11                        0.0        0.0        0.0        0.0
2004-02-12                        0.0        0.0        0.0        0.0
...                               ...        ...        ...        ...
2017-05-31                        0.0        0.0        0.0        0.0
2017-06-01                        0.0        0.0        0.0        0.0
2017-06-02                        0.0        0.0        0.0        0.0
2017-06-05                        0.0        0.0        0.0        0.0
2017-06-06                        0.0        0.0        0.0        0.0
2017-06-07                        0.0        0.0        0.0        0.0
2017-06-08                        0.0        0.0        0.0        0.0
2017-06-09                        0.0        0.0        0.0        0.0
2017-06-12                        0.0        0.0        0.0        0.0
2017-06-13                        0.0        0.0        0.0        0.0
2017-06-14                        0.0        0.0        0.0        0.0
2017-06-16                        0.0        0.0        0.0        0.0
2017-06-19                        0.0        0.0        0.0        0.0
2017-06-20                        0.0        0.0        0.0        0.0
2017-06-21                        0.0        0.0        0.0        0.0
2017-06-22                        0.0        0.0        0.0        0.0
2017-06-23                        0.0        0.0        0.0        0.0
2017-06-26                        0.0        0.0        0.0        0.0
2017-06-27                        0.0        0.0        0.0        0.0
2017-06-28                        0.0        0.0        0.0        0.0
2017-06-29                        0.0        0.0        0.0        0.0
2017-06-30                        0.0        0.0        0.0        0.0
2017-07-03                        0.0        0.0        0.0        0.0
2017-07-04                        0.0        0.0        0.0        0.0
2017-07-05                        0.0        0.0        0.0        0.0
2017-07-06                        0.0        0.0        0.0        0.0
2017-07-07                        0.0        0.0        0.0        0.0
2017-07-10                        0.0        0.0        0.0        0.0
2017-07-11                        0.0        0.0        0.0        0.0
2017-07-12                        0.0        0.0        0.0        0.0

                                                                        \
data_liquidacao_financeira 2017-06-01 2017-07-03 2017-08-01 2017-10-02
date
2004-01-02                        0.0        0.0        0.0       0.00
2004-01-05                        0.0        0.0        0.0       0.00
2004-01-06                        0.0        0.0        0.0       0.00
2004-01-07                        0.0        0.0        0.0       0.00
2004-01-08                        0.0        0.0        0.0       0.00
2004-01-09                        0.0        0.0        0.0       0.00
2004-01-12                        0.0        0.0        0.0       0.00
2004-01-13                        0.0        0.0        0.0       0.00
2004-01-14                        0.0        0.0        0.0       0.00
2004-01-15                        0.0        0.0        0.0       0.00
2004-01-16                        0.0        0.0        0.0       0.00
2004-01-19                        0.0        0.0        0.0       0.00
2004-01-20                        0.0        0.0        0.0       0.00
2004-01-21                        0.0        0.0        0.0       0.00
2004-01-22                        0.0        0.0        0.0       0.00
2004-01-23                        0.0        0.0        0.0       0.00
2004-01-26                        0.0        0.0        0.0       0.00
2004-01-27                        0.0        0.0        0.0       0.00
2004-01-28                        0.0        0.0        0.0       0.00
2004-01-29                        0.0        0.0        0.0       0.00
2004-01-30                        0.0        0.0        0.0       0.00
2004-02-02                        0.0        0.0        0.0       0.00
2004-02-03                        0.0        0.0        0.0       0.00
2004-02-04                        0.0        0.0        0.0       0.00
2004-02-05                        0.0        0.0        0.0       0.00
2004-02-06                        0.0        0.0        0.0       0.00
2004-02-09                        0.0        0.0        0.0       0.00
2004-02-10                        0.0        0.0        0.0       0.00
2004-02-11                        0.0        0.0        0.0       0.00
2004-02-12                        0.0        0.0        0.0       0.00

In [8]:
estoque_aberto.to_excel('estoque_swap.xlsx')

In [9]:
pvt_hist.to_excel('estoque_hist.xlsx')